# Name of workflow
name: Cypress Component Tests

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # environment: MONGODB_URI

    # # Define env secret at job level
    # env:
    #   MONGODB_URI: ${{ secrets.MONGODB_URI }}

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      # Install dependencies
      - name: 🧰 Install Dependencies
        run: npm install

      # # Debugging env
      # - name: Debug MongoDB URI
      #   run: |
      #     if [ -z "$MONGODB_URI" ]; then
      #       echo "MONGODB_URI is not set!"
      #     else
      #       echo "$MONGODB_URI is set."
      #     fi

      # Build dist files
      - name: Build server and client
        run: npm run build

      # # Run server before E2E test
      # - name: Startup server
      #   run: npm run start & npx wait-on http://localhost:3001
        
      # Run Cypress
      - name: Run Cypress Component Test
        run: npm run test-component
      
      # - name: Run Cypress E2E Test
      #   run: npm run test